---
extends: default

rules:
  indentation:
    indent-sequences: true
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  comments-indentation: enable
